models:
    - name: crowd
    - name: human
    - name: beer
    - name: chocolate_cereals
    - name: cigarettes
    - name: coffeepads
    - name: deodorant
    - name: filler
    - name: ice_tea
    - name: muesli_cereals
    - name: oblates
    - name: pringles
    - name: twine
    - name: wd40
    - name: brush
    - name: chocosticks
    - name: coffee
    - name: coke
    - name: fanta
    - name: fresh_milk
    - name: meadow_milk
    - name: noodles
    - name: peanut
    - name: red_bull
    - name: tape
    - name: yellow_candle
    - name: lemon
    - name: mandarine
    - name: mints
    - name: bubblemint
    - name: bowl