models:
    - name: human
    - name: apple
    - name: bubble_gum
    - name: bean_sauce
    - name: egg_stars
    - name: lotion
    - name: sponge
    - name: water
    - name: barbecue_chips
    - name: chocolates
    - name: gram_soup
    - name: orange_juice
    - name: toilet_paper
    - name: beer
    - name: cloth
    - name: green_tea
    - name: papaya_milk
    - name: tomato_chips
    - name: biscuits
    - name: coco_balls
    - name: honey_chips
    - name: plate
    - name: toothpaste
    - name: bowl
    - name: coconut_cereals
    - name: lemon
    - name: soap
    - name: pure_milk
    - name: tray